"""
Pydantic v2 Schemas for Equipment Health Agent.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, model_validator


class EquipmentInput(BaseModel):
    """Input payload for Equipment Health Agent evaluation."""
    equipment_id: str = Field(default="EQP-HVAC-01", description="Unique equipment identifier")
    equipment_type: str = Field(default="HVAC", description="Type of asset: 'HVAC', 'Chiller', 'Pump', or 'AHU'")
    runtime_hours: float = Field(default=5000.0, ge=0.0, description="Total cumulative operating hours")
    motor_current: float = Field(default=25.0, ge=0.0, description="Operating motor current in Amperes")
    temperature: float = Field(default=65.0, description="Operating temperature in degrees Celsius")
    vibration: float = Field(default=1.5, ge=0.0, description="Vibration amplitude in mm/s or g-force")
    maintenance_history: List[str] = Field(default_factory=list, description="Recent maintenance activity logs")
    error_codes: List[str] = Field(default_factory=list, description="Active diagnostic error fault codes")
    wear_level: float = Field(default=0.2, ge=0.0, le=1.0, description="Component mechanical wear level (0.0=New, 1.0=Worn Out)")

    # Legacy field support
    active_faults: Optional[List[str]] = Field(default=None, description="Legacy active faults list")

    @model_validator(mode="before")
    @classmethod
    def reconcile_legacy_fields(cls, values: Any) -> Any:
        if isinstance(values, dict):
            if "active_faults" in values and values["active_faults"] and "error_codes" not in values:
                values["error_codes"] = values["active_faults"]
        return values


class EquipmentRecommendation(BaseModel):
    """Predictive maintenance recommendation generated by Equipment Health Agent."""
    health_score: float = Field(..., ge=0.0, le=100.0, description="Overall asset health score from 0 (Failed) to 100 (Optimal)")
    remaining_useful_life_days: float = Field(..., ge=0.0, description="Estimated Remaining Useful Life (RUL) in operating days")
    maintenance_recommendation: str = Field(..., description="Actionable maintenance advice and prescribed procedure")
    failure_probability: float = Field(..., ge=0.0, le=1.0, description="Probability of catastrophic failure within 30 days")
    urgency: str = Field(..., description="Severity level: 'low', 'medium', 'high', or 'critical'")
    affected_equipment: str = Field(..., description="Target equipment identifier and module name")
    reasoning: str = Field(..., description="Engineering rationale detailing root cause and telemetry symptoms")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence score of the evaluation")


class EquipmentAgentResponse(BaseModel):
    """Standardized response output structure for Equipment Health Agent."""
    agent: str = Field(default="EquipmentAgent", description="Agent identifier name")
    status: str = Field(..., description="Execution status: 'success', 'fallback', or 'error'")
    recommendation: EquipmentRecommendation = Field(..., description="Structured equipment health recommendation")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Overall evaluation confidence level")
    reasoning: str = Field(..., description="Human-readable decision explanation")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Telemetry metrics and execution metadata")


# Legacy schema compatibility aliases
EquipmentState = EquipmentInput

class EquipmentOutput(BaseModel):
    maintenance_required: bool = Field(..., description="Whether maintenance is immediately required")
    predicted_failure_days: int = Field(..., description="Predicted days until component failure")
    reasoning: str = Field(..., description="Explanation of equipment health decision")
