"""
Pydantic v2 Schemas for the Energy Agent.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, model_validator


class BatterySchedule(BaseModel):
    """Details for energy storage battery operation."""
    action: str = Field(..., description="Action to take: 'charge', 'discharge', or 'idle'")
    rate_pct: float = Field(..., ge=0.0, le=100.0, description="Battery charge/discharge rate percentage")


class LoadShiftDetail(BaseModel):
    """Details for load shifting recommendations."""
    target_appliance: str = Field(..., description="Appliance or system targeted for load shift")
    kw_reduction: float = Field(..., ge=0.0, description="Target power reduction in kW")
    recommended_start: str = Field(..., description="Recommended shift start time (HH:MM format)")
    recommended_end: str = Field(..., description="Recommended shift end time (HH:MM format)")


class EnergyInput(BaseModel):
    """Input payload for Energy Agent optimization."""
    electricity_tariff: float = Field(default=0.25, ge=0.0, description="Current electricity tariff in $/kWh")
    battery_level: float = Field(default=50.0, ge=0.0, le=100.0, description="Battery charge level in percentage")
    solar_production: float = Field(default=0.0, ge=0.0, description="Current solar power production in kW")
    hvac_consumption: float = Field(default=100.0, ge=0.0, description="Current HVAC power draw in kW")
    predicted_occupancy: int = Field(default=50, ge=0, description="Predicted occupancy count")
    temperature: float = Field(default=72.0, description="Ambient building temperature in Fahrenheit")
    weather: str = Field(default="Clear", description="Current weather condition")
    grid_pricing: str = Field(default="off_peak", description="Grid pricing tier: 'off_peak', 'mid_peak', 'on_peak', or 'critical_peak'")
    peak_demand: float = Field(default=200.0, ge=0.0, description="Peak load limit threshold in kW")
    historical_energy_usage: List[float] = Field(default_factory=list, description="Recent historical hourly usage in kW")

    # Legacy field compatibility support
    current_kw: Optional[float] = Field(default=None, description="Legacy power draw in kW")
    peak_limit_kw: Optional[float] = Field(default=None, description="Legacy peak load limit in kW")

    @model_validator(mode="before")
    @classmethod
    def reconcile_legacy_fields(cls, values: Any) -> Any:
        if isinstance(values, dict):
            if "current_kw" in values and values["current_kw"] is not None and "hvac_consumption" not in values:
                values["hvac_consumption"] = float(values["current_kw"])
            if "peak_limit_kw" in values and values["peak_limit_kw"] is not None and "peak_demand" not in values:
                values["peak_demand"] = float(values["peak_limit_kw"])
        return values


class EnergyRecommendation(BaseModel):
    """Core recommendation generated by Energy Agent."""
    recommendation: str = Field(..., description="Actionable summary of energy optimization decision")
    battery_schedule: BatterySchedule = Field(..., description="Battery charge/discharge schedule")
    grid_usage_kw: float = Field(..., ge=0.0, description="Estimated grid power draw in kW")
    load_shifting: LoadShiftDetail = Field(..., description="Load shifting specification")
    cost_estimation: float = Field(..., description="Estimated total cost for the operational cycle in USD")
    energy_savings: float = Field(..., description="Estimated cost savings achieved in USD")
    reasoning: str = Field(..., description="Detailed step-by-step rationale behind decisions")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of recommendation")


class EnergyAgentResponse(BaseModel):
    """Standardized output response format for Energy Agent."""
    agent: str = Field(default="EnergyAgent", description="Agent name identifier")
    status: str = Field(..., description="Execution status: 'success', 'fallback', or 'error'")
    recommendation: EnergyRecommendation = Field(..., description="Structured energy recommendation payload")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Overall confidence level")
    reasoning: str = Field(..., description="Human-readable decision explanation")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Execution metrics and telemetry")


# Legacy schema aliases for backward compatibility
EnergyState = EnergyInput

class EnergyOutput(BaseModel):
    shedding_recommended: bool = Field(..., description="Whether to trigger load shedding")
    target_kw_reduction: float = Field(..., description="Amount of kW to shed")
    reasoning: str = Field(..., description="Explanation of energy decision")
